extends "res://addons/gut/test.gd"

# Unit tests for the procedural audio generator (scripts/sfx.gd). Sfx produces
# AudioStreamWAV data with no scene/tree dependencies, so it is fully testable:
# we assert on the stream format and the generated byte-length.

const RATE: int = 22050


func test_tone_has_expected_format_and_length() -> void:
	var s: AudioStreamWAV = Sfx.tone(440.0, 0.1, 0.5, RATE)
	assert_not_null(s)
	assert_eq(s.format, AudioStreamWAV.FORMAT_16_BITS)
	assert_eq(s.mix_rate, RATE)
	assert_false(s.stereo, "Clips are mono")
	# 16-bit mono => 2 bytes per sample.
	assert_eq(s.data.size(), int(0.1 * RATE) * 2)


func test_tone_can_loop() -> void:
	var s: AudioStreamWAV = Sfx.tone(200.0, 0.2, 0.4, RATE, true)
	assert_eq(s.loop_mode, AudioStreamWAV.LOOP_FORWARD)
	assert_eq(s.loop_end, int(0.2 * RATE))


func test_non_looping_tone_has_no_loop() -> void:
	var s: AudioStreamWAV = Sfx.tone(200.0, 0.2, 0.4, RATE)
	assert_eq(s.loop_mode, AudioStreamWAV.LOOP_DISABLED)


func test_sweep_length_matches_duration() -> void:
	var s: AudioStreamWAV = Sfx.sweep(600.0, 200.0, 0.15, 0.5, RATE)
	assert_eq(s.data.size(), int(0.15 * RATE) * 2)


func test_jingle_concatenates_notes() -> void:
	var freqs: PackedFloat32Array = PackedFloat32Array([440.0, 660.0, 880.0])
	var s: AudioStreamWAV = Sfx.jingle(freqs, 0.05, 0.5, RATE)
	var per_note: int = int(0.05 * RATE) * 2
	assert_eq(s.data.size(), per_note * 3)
